Repository MohammedOmar123/PenPals, pull requests merged in 2023-02, with the labels that each got.

#13 10 add feedback module and migration
  server/src/app.module.ts
  server/src/database/config.json
  server/src/database/migrations/20230216192145-create-feedback.js
  server/src/feedback/dto/create-feedback.dto.ts
  server/src/feedback/dto/update-feedback.dto.ts
  server/src/feedback/entities/feedback.entity.ts
  server/src/feedback/feedback.controller.spec.ts
  server/src/feedback/feedback.controller.ts
  server/src/feedback/feedback.module.ts
  server/src/feedback/feedback.service.spec.ts
  server/src/feedback/feedback.service.ts
  server/src/users/entities/user.entity.ts
Labels: Awaiting-review

#15 added missing columns and config js file
  server/.env.example
  server/.sequelizerc
  server/src/comments/comments.controller.ts
  server/src/comments/dto/index.ts
  server/src/database/config.js
  server/src/database/config.json
  server/src/database/migrations/20230214211316-create-user.ts
  server/src/database/migrations/20230214222342-create-projects.ts
  server/src/database/migrations/20230214224923-create-post.ts
  server/src/database/migrations/20230214231506-create-views.ts
  server/src/database/migrations/20230215000328-create-user-project.ts
  server/src/database/migrations/20230216192145-create-feedback.ts
  server/src/database/migrations/20230216194842-create-comments.ts
  server/src/feedback/dto/index.ts
  server/src/feedback/entities/index.ts
  server/src/feedback/feedback.controller.ts
  server/src/feedback/feedback.service.ts
Labels: Awaiting-review

#16 front-end setup
  client/.eslintrc.json
  client/.gitignore
  client/.vscode/settings.json
  client/README.md
  client/app/globals.css
  client/app/head.tsx
  client/app/layout.tsx
  client/app/page.module.css
  client/app/page.tsx
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/pages/api/hello.ts
  client/postcss.config.js
  client/public/favicon.ico
  client/public/next.svg
  client/public/thirteen.svg
  client/public/vercel.svg
  client/tailwind.config.js
  client/tsconfig.json
Labels: Awaiting-review

#18 complete front-end setup
  client/components/index.ts
  client/hooks/index.ts
  client/interfaces/index.ts
  client/services/axios.ts
  client/store/index.ts
  client/utils/constants.ts
  client/utils/endpoints.ts
  client/utils/functions.ts
  client/validation/index.ts
Labels: Awaiting-review

#20 setup e2e testing environment
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/comments/entities/comment.entity.ts
  server/src/database/config.js
  server/src/feedback/entities/feedback.entity.ts
  server/src/feedback/feedback.service.spec.ts
  server/src/posts/entities/post.entity.ts
  server/src/user-project/entities/user-project.entity.ts
  server/src/users/entities/user.entity.ts
  server/src/views/entities/view.entity.ts
  server/test/app.e2e-spec.ts
Labels: Awaiting-review

#21 Handled Signup and added test cases
  server/.sequelizerc
  server/.vscode/settings.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/SignupDto.dto.ts
  server/src/auth/dto/index.ts
  server/src/auth/dto/update-auth.dto.ts
  server/src/auth/entities/auth.entity.ts
  server/src/auth/entities/index.ts
  server/src/core/constant.ts
  server/src/core/database/config.js
  server/src/core/database/connection/config.ts
  server/src/core/database/connection/index.ts
  server/src/core/database/migrations/20230214211316-create-user.ts
  server/src/core/database/migrations/20230214222342-create-projects.ts
  server/src/core/database/migrations/20230214224923-create-post.ts
  server/src/core/database/migrations/20230214231506-create-views.ts
  server/src/core/database/migrations/20230215000328-create-user-project.ts
  server/src/core/database/migrations/20230216192145-create-feedback.ts
  server/src/core/database/migrations/20230216194842-create-comments.ts
  server/src/main.ts
  server/src/users/entities/user.entity.ts
  server/test/app.e2e-spec.ts
Labels: Awaiting-review

#24 added image column to the users table
  server/src/core/database/migrations/20230214211316-create-user.ts
  server/src/users/entities/user.entity.ts
Labels: Awaiting-review

#25 Created data seeders and factoy
  server/package-lock.json
  server/package.json
  server/src/core/database/factory/data.factory.ts
  server/src/core/database/migrations/20230214222342-create-projects.ts
  server/src/core/database/seeders/20230219034347-all_data_seeder.js
  server/src/projects/entities/project.entity.ts
Labels: Approved

#26 Created Custom exception filter
  server/src/core/HttpExceptionFilter/AllExceptions.filter.ts
  server/src/core/HttpExceptionFilter/index.ts
  server/src/core/constant.ts
  server/src/core/database/factory/data.factory.js
  server/src/main.ts
Labels: Approved

#27 Handled signIn route and refactor signup function and AllExceptionsFi…
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/SignInDto.dto.ts
  server/src/auth/dto/index.ts
  server/src/auth/dto/update-auth.dto.ts
  server/src/auth/entities/auth.entity.ts
  server/src/auth/entities/index.ts
  server/src/core/HttpExceptionFilter/AllExceptions.filter.ts
  server/src/core/constant.ts
  server/test/app.e2e-spec.ts
Labels: Awaiting-review

#29 Implemented Role based authentication and JWT based authentication
  server/package-lock.json
  server/package.json
  server/src/auth/Guards/roles.guard.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/decrator/getUser.decorator.ts
  server/src/auth/decrator/index.ts
  server/src/auth/decrator/roles.decorator.ts
  server/src/auth/enums/role.enum.ts
  server/src/auth/strategy/index.ts
  server/src/auth/strategy/jwt-auth-guard.ts
  server/src/auth/strategy/jwt.strategy.ts
  server/src/posts/posts.controller.ts
Labels: Awaiting-review

#39 Making statistics list section with edit some confgration
  client/app/globals.css
  client/app/layout.tsx
  client/app/page.tsx
  client/components/CustomSection/index.tsx
  client/components/Statistics/StatisticsItem.tsx
  client/components/Statistics/StatisticsList.tsx
  client/components/TitleSection/index.tsx
  client/interfaces/IStatisticsItem.tsx
  client/package-lock.json
  client/package.json
  client/public/icons/competition.svg
  client/public/icons/post.svg
  client/public/icons/student.svg
  client/public/icons/user.svg
  client/tailwind.config.js
  client/utils/constants.ts
  client/utils/constants.tsx
Labels: Awaiting-review

#41 created create project route and edited id column for all project ent…
  server/src/comments/entities/comment.entity.ts
  server/src/core/constant.ts
  server/src/feedback/entities/feedback.entity.ts
  server/src/posts/entities/post.entity.ts
  server/src/projects/dto/create-project.dto.ts
  server/src/projects/entities/project.entity.ts
  server/src/projects/projects.controller.ts
  server/src/projects/projects.service.ts
  server/src/user-project/entities/user-project.entity.ts
Labels: Awaiting-review

#44 handled create feedback route.
  server/src/core/constant.ts
  server/src/feedback/dto/create-feedback.dto.ts
  server/src/feedback/feedback.controller.ts
  server/src/feedback/feedback.service.ts
Labels: Awaiting-review

#45 Added test cases for POST api/v1/projects and POST api/v1/feedback routes
  server/package.json
  server/src/core/database/seeders/20230219034347-all_data_seeder.js
  server/src/projects/dto/create-project.dto.ts
  server/test/app.e2e-spec.ts
Labels: Approved

#47 Implemented email verification
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/Verify.dto.ts
  server/src/auth/dto/index.ts
  server/src/core/constant.ts
  server/src/core/database/factory/data.factory.js
  server/src/core/database/migrations/20230214211316-create-user.ts
  server/src/core/database/seeders/20230219034347-all_data_seeder.js
  server/src/core/verificationMailPage.ts
  server/src/users/entities/user.entity.ts
  server/test/app.e2e-spec.ts
Labels: Approved

#42 [frontend] create Latest Notification section and Avatar component and UserInfo Component.
  client/app/page.tsx
  client/components/Avatar/index.tsx
  client/components/LatestNotification/NotificationItem.tsx
  client/components/LatestNotification/NotificationList.tsx
  client/components/UserInfo/index.tsx
  client/interfaces/other/INotificationsItem.tsx
  client/interfaces/other/IStatisticsItem.tsx
  client/interfaces/props/IAvatar.tsx
  client/interfaces/props/IUserInfo.tsx
  client/public/favicon.ico
  client/public/images/userImg.png
  client/public/next.svg
  client/public/thirteen.svg
  client/public/vercel.svg
  client/utils/constants.tsx
Labels: Request-change

#49 Created email services class to make the code more readable
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/email.service.ts
  server/src/core/constant.ts
Labels: Awaiting-review

#50 create notifications module and migrations
  .vscode/settings.json
  server/package.json
  server/src/app.module.ts
  server/src/core/database/migrations/20230228113621-create-notifications.ts
  server/src/notifications/dto/create-notification.dto.ts
  server/src/notifications/dto/update-notification.dto.ts
  server/src/notifications/entities/notification.entity.ts
  server/src/notifications/notifications.controller.spec.ts
  server/src/notifications/notifications.controller.ts
  server/src/notifications/notifications.module.ts
  server/src/notifications/notifications.service.spec.ts
  server/src/notifications/notifications.service.ts
  server/src/posts/entities/post.entity.ts
Labels: Awaiting-review

#51 handled updating a project
  server/package-lock.json
  server/src/core/constant.ts
  server/src/core/pipes/ParamValidation.pipe.ts
  server/src/projects/dto/create-project.dto.ts
  server/src/projects/projects.controller.ts
  server/src/projects/projects.service.ts
Labels: Awaiting-review
