Repository MohammedOmar123/PenPals, pull requests merged in 2023-03, with the labels that each got.

#53 created admin dashboard layout routing.
  client/app/dashboard/layout.tsx
  client/app/dashboard/page.tsx
  client/app/page.tsx
  client/components/Aside/index.tsx
  client/components/index.ts
Labels: Approved

#56 33 handle deleting project update feedback
  server/src/auth/Guards/roles.guard.ts
  server/src/auth/decorators/getUser.decorator.ts
  server/src/auth/decorators/index.ts
  server/src/auth/decorators/roles.decorator.ts
  server/src/core/constant.ts
  server/src/feedback/feedback.controller.ts
  server/src/feedback/feedback.service.ts
  server/src/posts/posts.controller.ts
  server/src/posts/posts.service.ts
  server/src/projects/projects.controller.ts
  server/src/projects/projects.service.ts
  server/test/app.e2e-spec.ts
Labels: Approved

#58 Handled Verified email and Handled resend email functionality.
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/index.ts
  server/src/auth/dto/resend-email.dto.ts
  server/src/auth/dto/sign-in.dto.ts
  server/src/auth/dto/sign-up.dto.ts
  server/src/auth/email.service.ts
  server/src/auth/strategy/jwt.strategy.ts
  server/src/core/HttpExceptionFilter/EmailNotConfirmedException.filter.ts
  server/src/core/HttpExceptionFilter/index.ts
  server/src/core/constant.ts
  server/src/core/database/migrations/20230214211316-create-user.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
Labels: Approved

#55 [backend-caching] Used CacheModule to chach most get requests.
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/comments/comments.controller.ts
  server/src/feedback/feedback.controller.ts
  server/src/notifications/notifications.controller.ts
  server/src/posts/posts.controller.ts
  server/src/projects/dto/create-project.dto.ts
  server/src/projects/projects.controller.ts
  server/src/user-project/user-project.controller.ts
  server/src/views/views.controller.ts
Labels: Awaiting-review

#68 Handled /me endpoint
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: Awaiting-review

#74 update colors in tailwind config file
  client/.gitignore
  client/app/layout.tsx
  client/tailwind.config.js
Labels: Awaiting-review

#76 editing tailwind config.
  client/tailwind.config.js
Labels: Awaiting-review

#75 36 delete routes api v1 feedback
  server/src/core/constant.ts
  server/src/feedback/feedback.controller.ts
  server/src/feedback/feedback.service.ts
Labels: Awaiting-review

#77 30 routes get api v1 users
  server/src/users/dto/create-user.dto.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: Awaiting-review

#79 handled file structure routing and pages inside app folder for client…
  client/app/dashboard/posts/page.tsx
  client/app/dashboard/settings/page.tsx
  client/app/dashboard/users/page.tsx
  client/app/login/page.tsx
  client/app/posts/layout.tsx
  client/app/posts/page.tsx
  client/app/register/page.tsx
  client/app/user/[userId]/page.tsx
  client/app/user/[userId]/post/[postId]/edit/page.tsx
  client/app/user/[userId]/post/[postId]/page.tsx
  client/app/user/[userId]/post/create/page.tsx
Labels: Awaiting-review

#78 72 handle notification route
  server/src/app.module.ts
  server/src/auth/Guards/roles.guard.ts
  server/src/auth/strategy/jwt.strategy.ts
  server/src/core/database/migrations/20230228113621-create-notifications.ts
  server/src/main.ts
  server/src/notification/dto/create-notification.dto.ts
  server/src/notification/dto/update-notification.dto.ts
  server/src/notification/entities/notification.entity.ts
  server/src/notification/notification.controller.spec.ts
  server/src/notification/notification.controller.ts
  server/src/notification/notification.module.ts
  server/src/notification/notification.service.spec.ts
  server/src/notification/notification.service.ts
  server/src/notifications/dto/create-notification.dto.ts
  server/src/notifications/notifications.controller.spec.ts
  server/src/notifications/notifications.controller.ts
  server/src/notifications/notifications.module.ts
  server/src/notifications/notifications.service.ts
  server/src/posts/entities/post.entity.ts
  server/src/users/entities/user.entity.ts
Labels: Awaiting-review

#81 [frontend] Create navbar and Button components
  client/app/layout.tsx
  client/components/Avatar/index.tsx
  client/components/Button/index.tsx
  client/components/Navbar/index.tsx
  client/components/UserInfo/index.tsx
  client/interfaces/props/IAvatar.tsx
  client/interfaces/props/IButton.tsx
  client/interfaces/props/IUserInfo.tsx
  client/public/images/logo.png
Labels: Approved

#82 Add seed data, and fix tests
  server/package-lock.json
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/sign-up.dto.ts
  server/src/core/constant.ts
  server/src/core/database/factory/data.factory.js
  server/src/core/database/seeders/20230219034347-all_data_seeder.js
  server/src/notification/notification.controller.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
  server/test/app.e2e-spec.ts
Labels: Awaiting-review, Approved

#86 fixed the token in the email
  server/src/auth/auth.service.ts
Labels: Approved

#84 83 sign up sign in front end
  client/.gitignore
  client/app/globals.css
  client/app/head.tsx
  client/app/layout.tsx
  client/app/login/page.tsx
  client/app/page.tsx
  client/app/register/page.tsx
  client/app/wait-verified/page.tsx
  client/components/Auth/AuthContainer.tsx
  client/components/Button/index.tsx
  client/components/FormikControl/Input.tsx
  client/components/FormikControl/Login.tsx
  client/components/FormikControl/Register.tsx
  client/components/FormikControl/TextError.tsx
  client/components/FormikControl/index.tsx
  client/components/Header/index.tsx
  client/components/Loading/index.tsx
  client/components/Navbar/index.tsx
  client/components/Overlay/index.tsx
  client/hooks/auth.hook.tsx
  client/interfaces/other/IRegisterFrom.tsx
  client/interfaces/other/ISigninForm.tsx
  client/interfaces/other/IUser.tsx
  client/interfaces/props/IAuthContainer.tsx
  client/interfaces/props/IButton.tsx
  client/interfaces/props/ISignInHeader.tsx
  client/services/ApiService.ts
  client/services/JwtService.ts
  client/services/axios.ts
  client/store/AuthStore.tsx
  client/store/ThemeStore.tsx
  client/tailwind.config.js
  client/tsconfig.json
  client/utils/constants.tsx
  client/utils/endpoints.ts
  client/validation/register.ts
  client/validation/signin.ts
  server/src/main.ts
Labels: Approved

#88 edit dashboard layout style and main page section.
  client/app/dashboard/layout.tsx
  client/app/dashboard/page.tsx
  client/components/Aside/index.tsx
  client/components/Button/index.tsx
  client/components/LatestNotification/NotificationItem.tsx
  client/components/LatestNotification/NotificationList.tsx
  client/components/Navbar/index.tsx
  client/components/Statistics/StatisticsItem.tsx
  client/components/Statistics/StatisticsList.tsx
  client/components/TitleSection/index.tsx
  client/interfaces/other/INotificationsItem.tsx
  client/utils/constants.tsx
Labels: Awaiting-review
